title: Object Detection
inputs:
    input0:
        source: H264_VID
        width: 1280
        height: 768
        video_path: /opt/edgeai-test-data/videos/video0_1280_768.h264
models:
    model0:
        model_path: /opt/model_zoo/TFL-OD-2020-ssdLite-mobDet-DSP-coco-320x320
        viz-threshold: 0.6
    model1:
        model_path: /opt/model_zoo/ONR-OD-8200-yolox-nano-lite-mmdet-coco-416x416
        viz-threshold: 0.6
outputs:
    output0:
        sink: RTOS_DISPLAY
        width: 1920
        height: 1080
    output1:
        sink: H264_ENCODE
        width: 1920
        height: 1080
        output_path: /opt/edgeai-test-data/output/output_video0.h264
    output2:
        sink: IMG_DIR
        width: 1920
        height: 1080
        output_path: /opt/edgeai-test-data/output/
flows:
    flow0:
        pipeline: [input0,model1,output0]
        mosaic:
            - [320,150,1280,720]