title: Semantic Segmentation
inputs:
    input0:
        source: VIDEO
        width: 1280
        height: 768
        video_path: /opt/edgeai-test-data/videos/video0_1280_768.h264
models:
    model0:
        model_path: /opt/model_zoo/TFL-SS-2580-deeplabv3_mobv2-ade20k32-mlperf-512x512
        alpha: 0.5
    model1:
        model_path: /opt/model_zoo/ONR-SS-8610-deeplabv3lite-mobv2-ade20k32-512x512
        alpha: 0.5
outputs:
    output0:
        sink: RTOS_DISPLAY
        width: 1920
        height: 1080
    output1:
        sink: H264_ENCODE
        width: 1920
        height: 1088
        output_path: /opt/edgeai-test-data/output/output_video0.h264
    output2:
        sink: IMG_DIR
        width: 1920
        height: 1080
        output_path: /opt/edgeai-test-data/output/
flows:
    flow0:
        pipeline: [input0,model1,output0]
        mosaic:
            - [320,150,1280,720]