title: Multi Input Multi Inference
inputs:
    input0:
        source: RAW_IMG
        width: 1280
        height: 720
        format: NV12
        image_path: /opt/edgeai-test-data/raw_images/tiovx_apps/
    input1:
        source: H264_VID
        width: 1280
        height: 768
        video_path: /opt/edgeai-test-data/videos/video0_1280_768.h264
models:
    model0:
        model_path: /opt/model_zoo/TFL-CL-0000-mobileNetV1-mlperf
        topN: 5
    model1:
        model_path: /opt/model_zoo/ONR-OD-8200-yolox-nano-lite-mmdet-coco-416x416
        viz-threshold: 0.4
    model2:
        model_path: /opt/model_zoo/ONR-OD-8200-yolox-nano-lite-mmdet-coco-416x416
        viz-threshold: 0.6
    model3:
        model_path: /opt/model_zoo/ONR-SS-8610-deeplabv3lite-mobv2-ade20k32-512x512
        alpha: 0.5
outputs:
    output0:
        sink: LINUX_DISPLAY
        width: 1920
        height: 1080
    output1:
        sink: H264_ENCODE
        width: 1920
        height: 1080
        output_path: /opt/edgeai-test-data/output/output_video0.h264
    output2:
        sink: IMG_DIR
        width: 1920
        height: 1080
        output_path: /opt/edgeai-test-data/output/
flows:
    flow0:
        pipeline: [input0,model0,output0]
        mosaic:
            - [320,150,640,360]
    flow1:
        pipeline: [input0,model1,output0]
        mosaic:
            - [960,150,640,360]
    flow2:
        pipeline: [input1,model2,output0]
        mosaic:
            - [320,510,640,360]
    flow3:
        pipeline: [input1,model3,output0]
        mosaic:
            - [960,510,640,360]