title: Image classification
inputs:
    input0:
        source: RTOS_CAM
        width: 1920
        height: 1080
        sensor-name: imx390
        channel_mask: 00000001
        ldc: True
    input1:
        source: LINUX_CAM
        width: 1920
        height: 1080
        sensor-name: imx219
        device: /dev/video-rpi-cam0
        subdev: /dev/video-rpi-subdev0
    input2:
        source: RAW_IMG
        width: 1280
        height: 720
        framerate: 1
        format: NV12
        image_path: /opt/edgeai-test-data/raw_images/tiovx_apps/
models:
    model0:
        model_path: /opt/model_zoo/TFL-CL-0000-mobileNetV1-mlperf
        topN: 5
    model1:
        model_path: /opt/model_zoo/ONR-CL-6360-regNetx-200mf
        topN: 5
outputs:
    output0:
        sink: RTOS_DISPLAY
        width: 1920
        height: 1080
    output1:
        sink: LINUX_DISPLAY
        width: 1920
        height: 1080
flows:
    flow0:
        pipeline: [input2,model0,output0]
        mosaic:
            - [320,150,1280,720]