title: "Multi Input Single Inference"
log_level: 2
inputs:
    input0:
        source: camera
        width: 1920
        height: 1080
        camera-id: 0
    input1:
        source: camera
        width: 1920
        height: 1080
        camera-id: 1
    input2:
        source: camera
        width: 1920
        height: 1080
        camera-id: 2
    input3:
        source: camera
        width: 1920
        height: 1080
        camera-id: 3
models:
    model0:
        model_path: /opt/model_zoo/TFL-CL-0000-mobileNetV1-mlperf
        topN: 5
    model1:
        model_path: /opt/model_zoo/ONR-CL-6360-regNetx-200mf
        topN: 5
    model2:
        model_path: /opt/model_zoo/ONR-OD-8020-ssd-lite-mobv2-mmdet-coco-512x512
        viz_threshold: 0.6
    model3:
        model_path: /opt/model_zoo/TFL-SS-2580-deeplabv3_mobv2-ade20k32-mlperf-512x512
        alpha: 0.4
outputs:
    output0:
        sink: display
        width: 1920
        height: 1080
    output1:
        sink: /opt/edgeai-test-data/output/output_image.nv12
        width: 1920
        height: 1080
    output2:
        sink: /opt/edgeai-test-data/output/
        width: 1920
        height: 1080

flows:
    flow0: [input0,model2,output0,[320,150,640,360]]
    flow1: [input1,model2,output0,[960,150,640,360]]
    flow2: [input2,model2,output0,[320,540,640,360]]
    flow3: [input3,model2,output0,[960,540,640,360]]